services:
  - type: web
    name: BrowserBattleChallenge
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: daphne session_auth.asgi:application -p $PORT -b 0.0.0.0
    envVars:
      - key: DEBUG
        value: True
      - key: SECRET_KEY
        value: 'django-insecure-1*ingqfrogn*u&&%=df6zu5)4imw-b#bm!t*vg0g_ze_-k*_0s'
      - key: DATABASE_URL
        fromDatabase:
          name: bbc_database
          property: connectionString
      - key: PYTHONPATH
        value: .
    autoDeploy: true
