services:
  - type: web
    name: your-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn session_auth.wsgi:application
    envVars:
      - key: DEBUG
        value: True
      - key: SECRET_KEY
        value: 'django-insecure-1*ingqfrogn*u&&%=df6zu5)4imw-b#bm!t*vg0g_ze_-k*_0s'
      - key: DATABASE_URL
        fromDatabase:
          name: bbc_database
          property: connectionString
    autoDeploy: true
