# Generated by Django 4.0.1 on 2023-10-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Abcd',
        ),
    ]
