# Generated by Django 4.0.1 on 2023-10-03 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hero_stats', '0002_delete_abcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_health', models.IntegerField(default=20)),
                ('base_damage', models.IntegerField(default=2)),
                ('base_armor', models.IntegerField(default=0)),
                ('base_speed', models.IntegerField(default=1)),
                ('base_strength', models.IntegerField(default=5)),
                ('base_agility', models.IntegerField(default=5)),
                ('base_intelligence', models.IntegerField(default=5)),
                ('level', models.IntegerField(default=1)),
                ('expirience', models.IntegerField(default=0)),
                ('current_health', models.IntegerField(default=0)),
                ('max_health', models.IntegerField(default=0)),
                ('min_dmg', models.IntegerField(default=0)),
                ('max_dmg', models.IntegerField(default=0)),
                ('armor', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('agility', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hero_stats',
            },
        ),
    ]
