# Generated by Django 4.0.1 on 2023-10-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herostats',
            name='agility',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='current_health',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='intelligence',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='max_dmg',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='max_health',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='min_dmg',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='speed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='strength',
            field=models.IntegerField(default=5),
        ),
    ]
