# Generated by Django 4.0.1 on 2023-10-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0004_alter_herostats_agility_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herostats',
            old_name='expirience',
            new_name='current_expirience',
        ),
    ]
