# Generated by Django 4.0.1 on 2023-10-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0005_rename_expirience_herostats_current_expirience'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostats',
            name='next_level_expirience',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='base_agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='base_intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='base_strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='intelligence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='herostats',
            name='strength',
            field=models.IntegerField(default=0),
        ),
    ]
