# Generated by Django 4.0.1 on 2023-10-04 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0006_herostats_next_level_expirience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herostats',
            name='speed',
            field=models.FloatField(default=1.0),
        ),
    ]
