# Generated by Django 4.0.1 on 2024-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0007_alter_herostats_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostats',
            name='prev_level_expirience',
            field=models.IntegerField(default=30),
        ),
    ]
