# Generated by Django 4.0.1 on 2024-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero_stats', '0009_rename_current_expirience_herostats_current_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herostats',
            name='hunt_levels_unlocked',
            field=models.IntegerField(default=1),
        ),
    ]
