# Generated by Django 4.0.1 on 2023-09-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='currency',
            table='currencies',
        ),
    ]
