# Generated by Django 4.0.1 on 2023-09-24 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField(default=dict)),
                ('next_item_id', models.PositiveIntegerField(default=1)),
                ('weapon_left', models.JSONField(default=dict)),
                ('weapon_right', models.JSONField(default=dict)),
                ('body_armor', models.JSONField(default=dict)),
                ('gloves', models.JSONField(default=dict)),
                ('boots', models.JSONField(default=dict)),
                ('helmet', models.JSONField(default=dict)),
                ('belt', models.JSONField(default=dict)),
                ('amulet', models.JSONField(default=dict)),
                ('ring_left', models.JSONField(default=dict)),
                ('ring_right', models.JSONField(default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory',
            },
        ),
    ]
