# Generated by Django 4.0.1 on 2023-09-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinventory',
            name='inventory_grid',
            field=models.JSONField(default=list),
        ),
    ]
