# Generated by Django 4.0.1 on 2023-10-03 15:59

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_playerinventory_amulet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='amulet',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='belt',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='body_armor',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='boots',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='gloves',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='helmet',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='ring_left',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='ring_right',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='weapon_left',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
        migrations.AlterField(
            model_name='playerinventory',
            name='weapon_right',
            field=models.JSONField(default=inventory.models.default_inventory_slot_value),
        ),
    ]
