# Generated by Django 4.0.1 on 2024-06-27 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_playerinventory_amulet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerinventory',
            name='accumulated_stats',
            field=models.JSONField(default=dict),
        ),
    ]
