# Generated by Django 4.0.1 on 2024-06-27 01:36

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_playerinventory_accumulated_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerinventory',
            name='accumulated_stats',
            field=models.JSONField(default=inventory.models.default_accumulated_stats),
        ),
    ]
