# Generated by Django 4.2.4 on 2023-08-19 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='heroName',
            new_name='first_name',
        ),
    ]
