# Generated by Django 4.2.4 on 2023-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_heroname_userprofile_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
    ]
