# Generated by Django 4.2.4 on 2023-09-05 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_name',
            new_name='nick_name',
        ),
    ]
