# Generated by Django 4.2.4 on 2023-09-05 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_rename_user_name_userprofile_nick_name'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile_data',
        ),
    ]
